name: Laravel Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, mysql

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add server host key to known_hosts
        run: ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Copy install.sh to server
        run: scp scripts/install.sh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/install.sh

      - name: Set up environment variables
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          echo "Setting up environment variables..."
          export MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}"
          echo "MYSQL_ROOT_PASSWORD set to: $MYSQL_ROOT_PASSWORD"

      - name: Execute install.sh on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 필요한 패키지 설치
            sudo apt-get update
            sudo apt-get install -y expect

            # MySQL 루트 패스워드 전달
            expect -c '
              spawn bash /home/${{ secrets.SERVER_USER }}/install.sh
              expect "Enter MySQL root password: "
              send "$MYSQL_ROOT_PASSWORD\r"
              expect eof
            '

            # Laravel 프로젝트 설정
            sudo mkdir -p /home/${{ secrets.SERVER_USER }}/laravel
            sudo chown -R $USER:$USER /home/${{ secrets.SERVER_USER }}/laravel
            cd /home/${{ secrets.SERVER_USER }}/laravel

            # Git 초기화 및 소스 코드 다운로드
            git init
            git remote add origin https://github.com/BaekJinYoung/Example.git
            git fetch
            git checkout master
            git pull origin master
