name: Laravel Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, mysql

      - name: Install Composer dependencies
        run: composer install --no-progress --no-suggest --prefer-dist --optimize-autoloader

      - name: Start SSH Agent
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          sudo mkdir -p /home/${{ secrets.SERVER_USER }}/.ssh
          echo "$SSH_PRIVATE_KEY" > /home/${{ secrets.SERVER_USER }}/.ssh/authorized_keys
          sudo chmod 600 /home/${{ secrets.SERVER_USER }}/.ssh/authorized_keys
          ssh-add /home/${{ secrets.SERVER_USER }}/.ssh/authorized_keys


      - name: Add server host key to known_hosts
        run: |
          mkdir -p ~/.ssh || { echo "Failed to create .ssh directory"; exit 1; }
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts || { echo "Failed to add server host key to known_hosts"; exit 1; }

      - name: Copy install.sh to server
        run: scp scripts/install.sh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/home/${{ secrets.SERVER_USER }}/install.sh

      - name: Execute install.sh on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}

            # 필요한 패키지 설치
            sudo apt-get update
            sudo apt-get install -y mysql-server

            # MySQL 루트 비밀번호 설정
            sudo mysql -e "ALTER USER 'root'@'localhost' IDENTIFIED WITH 'mysql_native_password' BY '${MYSQL_ROOT_PASSWORD}'; FLUSH PRIVILEGES;"

            # Laravel 프로젝트 설정
            sudo mkdir -p /home/${{ secrets.SERVER_USER }}/laravel
            sudo chown -R $USER:$USER /home/${{ secrets.SERVER_USER }}/laravel
            cd /home/${{ secrets.SERVER_USER }}/laravel

            # Git 초기화 및 소스 코드 다운로드
            git init
            git remote add origin https://github.com/BaekJinYoung/Example.git
            git fetch
            git checkout master
            git pull origin master

            # install.sh 실행
            sudo -u ${{ secrets.SERVER_USER }} bash /home/${{ secrets.SERVER_USER }}/install.sh

            # 웹 서버 사용자로 소유자 변경
            sudo chown -R www-data:www-data /home/${{ secrets.SERVER_USER }}/laravel

            # 파일 권한 설정
            sudo find /home/${{ secrets.SERVER_USER }}/laravel -type f -exec chmod 644 {} \;
            sudo find /home/${{ secrets.SERVER_USER }}/laravel -type d -exec chmod 755 {} \;
            #
